### ISSUE TITLE
SSA and generics (go1.18)

### ISSUE THREAD

**Issue by ldez** [timakin/bodyclose#38]
Currently, SSA is not working with generics.

So your linter produces a panic when it is used with generics.

There is an issue open about that in the Go repository: https://github.com/golang/go/issues/48525

Inside golangci-lint, we have disabled your linters: https://github.com/golangci/golangci-lint/issues/2649

You have 2 solutions:
- waiting for a version of SSA that will support generics
- dropping the SSA analyzers and using something else to analyze the code.

Related to https://github.com/golang/go/issues/50558

**Comment by ldez** [comment]
SSA has been updated and it seems to work inside golangci-lint.

**Comment by ldez** [comment]
in fact the problem is still here

**Comment by ldez** [comment]
I did some more extensive testing and the issue seems to be resolved.

**Comment by ldez** [comment]
https://github.com/golangci/golangci-lint/issues/3086

**Comment by stevenh** [comment]
PR #41 fixes this, tested with the case in https://github.com/golangci/golangci-lint/issues/3086
```
~/chconn$ go vet -vettool=$(which bodyclose) ./...
~/chconn$
```
Yes that's no output all good :)
