### ISSUE TITLE
Vet regression case from update

### ISSUE THREAD

**Issue by benw10-1** [timakin/bodyclose#68]
Seeing stuff that didn't fail on [ed6a65f](https://github.com/timakin/bodyclose/commit/ed6a65f985e322234bc87d7052e39d450244e688) now failing on current commit.

Example:
`integrations/testbodyclose/test.go`
```go
package sandbox

import (
	"io"
	"net/http"
)

func Foo(req *http.Request) error {
	res, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	defer res.Body.Close()

	if res.StatusCode == 200 {
		body, err := io.ReadAll(res.Body)
		if err != nil {
			return err
		}
		_ = body

		return nil
	}

	return nil
}
```
Passes on [ed6a65f](https://github.com/timakin/bodyclose/commit/ed6a65f985e322234bc87d7052e39d450244e688), but fails with:
```
integrations/testbodyclose/test.go:10:35: response body must be closed
```
on master commit.

Can provide more examples similar to this if necessary, but would need to dig them up so didn't include in initial.

**Comment by ldez** [comment]
Other variants:

<details>
<summary>A</summary>

```go
package sandbox

import (
	"io"
	"net/http"
)

func Foo(req *http.Request) error {
	res, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}

	defer res.Body.Close()

	if res.StatusCode == 200 {
		return nil
	}

	io.ReadAll(res.Body)

	return nil
}
```

</details>

<details>
<summary>B</summary>

```go
func Foo(req *http.Request) error {
	res, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}

	defer res.Body.Close()

	for range res.StatusCode {
		return nil
	}

	io.ReadAll(res.Body)

	return nil
}
```

</details>

**Comment by ldez** [comment]
The problem is related to the way the graph is analyzed: the algorithm is always wrong if there is at least one `if`/`for`/`switch`/etc. and a defer at the top level.

**Comment by benw10-1** [comment]
Seems like it needs to be updated such that it doesn't fail if the parent branch explicitly defers the `Close` call instead of checking block by block without considering these cases.

I tested the below case as well and got fail:

`integrations/testbodyclose/test.go`

```
package sandbox

import (
	"net/http"
)

func Foo(req *http.Request) error {
	res, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	defer res.Body.Close()

	{
		_ = res.Body
	}

	return nil
}
```

Fails with:

```
integrations/testbodyclose/test.go:8:35: response body must be closed
```

**Comment by ldez** [comment]
Offtopic: a tip to collapse examples inside Markdown.

````html
<details><summary>foo</summary>

```
code
```

</details>
````

Result:

<details><summary>foo</summary>

```
code
```

</details>
